parameters:
  SDKType: client
  ServiceDirectory: not-specified # Set a default that breaks in obvious ways.
  Artifacts: []
  AdditionalModules: []

jobs:
- job: "Analyze"
  variables:
    - template: ../variables/globals.yml

  steps:
    - template: /eng/common/pipelines/templates/steps/analyze-pkg-props.yml
      parameters:
          ServiceDirectory: ${{parameters.ServiceDirectory}}
          Artifacts: ${{parameters.Artifacts}}